<nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <ul class="nav navbar-nav"><li>
          <form class="navbar-form navbar-left" role="search" method="post">
            <div class="form-group">
              <input class="form-control" placeholder="Filter by nodes" name="node" type="text" id="filter-nodes">
            </div>
            <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Submit</button>
          </form>
                </li>
                </ul>
            <ul class="nav navbar-nav navbar-right">
                    <li>
                        <p style="margin: 10px;"><a class="btn btn-success" href="<?php echo $this->url('application/default',array('controller' => 'index', 'action' => 'update')) ?>"><span class="glyphicon glyphicon-refresh"></span> <strong><?php echo $this->translate('Update Cache data') ?></strong></a></p>
                    </li>
                </ul>
        </div>
      </div>
</nav>

<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));

$scopes = array_keys($this->tabs);
?>
<div class="row">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
        <?php foreach ($scopes as $scope):?>
          <li <?php if ($scopes[0] == $scope):?> class="active" <?php endif;?>><a href="#<?php echo $scope ?>" data-toggle="tab"><?php echo $scope ?></a></li>
        <?php endforeach; ?>
    </ul>

    <div class="tab-content">
        <?php foreach ($scopes as $scope):?>
            <div class="tab-pane fade in <?php if ($scopes[0] == $scope):?>active<?php endif;?>" id="<?php echo $scope ?>">
                <!-- Table -->
                <table id="table-<?php echo $scope ?>" class="table table-hover table-condensed table-bordered">
                    <thead>
                        <tr class="active">
                            <th>ID <span class="glyphicon glyphicon-sort"></span></th>
                            <th>Email <span class="glyphicon glyphicon-sort"></span></th>
                            <th><div style="width: 107px;">Organization <span class="glyphicon glyphicon-sort"></span></div></th>
                            <th><div style="width: 75px;">SSH key <span class="glyphicon glyphicon-sort"></span></div></th>
                            <th>Access to nodes <span class="glyphicon glyphicon-sort"></span></th>
                            <th><div style="width: 99px;">Full Access <span class="glyphicon glyphicon-sort"></span></div></th>
                            <th>Validation <span class="glyphicon glyphicon-sort"></span></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->tabs[$scope] as $user):?>
                        <tr <?php if (count($user['validate']) > 0):?>class="danger"<?php endif; ?>>
                            <td><?php echo $user['id'] ?></td>
                            <td <?php if (strlen($user['email']) > 40):?>class="danger"<?php endif;?>><?php echo ((strlen($user['email']) > 40)?'Empty email':$user['email']) ?></td>
                            <td><?php echo ((isset($user['org_name']))?$user['org_name']:'none'); ?></td>
                            <td><a href="#" data-key="<?php echo $user['id'] ?>" data-toggle="modal" data-target="#sshModal">Show</a></td>
                            <td>
                                <ul>
                                <?php foreach ($user['nodes'] as $node): ?>
                                    <li><?php echo $node ?></li>
                                <?php endforeach;  ?>
                                </ul>
                            </td>
                            <td <?php if($user['systemteam']): ?>class="success"<?php endif;?>><?php echo ($user['systemteam'])?'YES':'NO' ?></td>
                            <td>
                                <ul>
                                <?php foreach ($user['validate'] as $node): ?>
                                    <li><?php echo $node ?></li>
                                <?php endforeach;  ?>
                                </ul>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php endforeach; ?>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="sshModal" tabindex="-1" role="dialog" aria-labelledby="sshModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="sshModalLabel">SSH Key</h4>
          </div>
          <div class="modal-body result" style="word-break: break-all;">

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <script type="text/javascript">
      // Waiting for the DOM ready...
      $(function(){

        // applied typeahead to the text input box
        $('#filter-nodes').typeahead({
            local: <?php echo json_encode($this->nodeList)?>
        });

          <?php foreach ($scopes as $scope):?>
          $("#table-<?php echo $scope ?>").tablesorter();
          <?php endforeach; ?>

          $('#sshModal').on('show.bs.modal', function (e) {
              var key = $(e.relatedTarget).attr('data-key');
              console.log(e);
              $.get( "<?php echo $this->url('application/default',array('controller' => 'index', 'action' => 'getkey')) ?>?key="+key, function( data ) {
                  $(".modal-body.result").html( data );
              });
            //if (!data) return e.preventDefault(); // stops modal from being shown
          });

      });

    </script>


</div>
